data:
    image: busybox
    volumes:
        - /var/lib/mysql

zabbix-db:
    image: zabbix/zabbix-db-mariadb
    volumes_from:
        - data
    volumes:
        - /etc/localtime/etc/localtime:ro
    environment:
        - MARIADB_USER=zabbix
        - MARIADB_PASS=zabbix

zabbix-server:
    image: zabbix/zabbix-3.0:latest
    volumes:
        - /etc/localtime/etc/localtime:ro
    environment:
        - ZS_DBHost=db
        - ZS_DBUser=zabbix
        - ZS_DBPassword=zabbix
    links:
        - zabbix-db
    ports:
        - 80:80
        - 10051:10051

zabbix-agent:
    image: zabbix/zabbix-3.0:latest
    volumes:
        - /etc/localtime/etc/localtime:ro
    ports:
        - 10050:10050
    links:
        - zabbix-server


